### ISSUE TITLE
Mod_auth_mellon and multiple Azure

### ISSUE THREAD

**Issue by KrisChro** [latchset/mod_auth_mellon#108]
Hi Everyone,

For several days now he has been trying to get mod_auth_mellon to work with more than one idp provider.
I have two different Azure instances with different users, but nowhere in the documentation do I see how I can force mod_auth_mellon to use different tenets depending on the location or domain.

i.e. if there is a connection to app1.mydomain.com it authenticates with Azure 1, if there is a connection to app2.mydomain.com it authenticates with Azure 2

Regards
Krzysztof Chrobak

**Comment by thijskh** [comment]
This is described in the README:

```
        # MellonIdPMetadataFile is the full path to the file which contains
        # metadata for the IdP you are authenticating against. This
        # directive is required. Multiple IdP metadata can be configured
        # by using multiple MellonIdPMetadataFile directives.
        #
        # If your lasso library is recent enough (higher than 2.3.5),
        # then MellonIdPMetadataFile will accept an XML file containing
        # descriptors for multiple IdP.
```

You need to use a discovery service or the probe discovery services in order to let the user pick the right IdP to use. Also see the readme for that.
