### ISSUE TITLE
lasso error -407 being thrown when attempting to logout

### ISSUE THREAD

**Issue by donraikes** [latchset/mod_auth_mellon#110]
I am runnin apache httpd 2.4.37 on oraclelinux 8.6 with mod_auth_mellon 0.14.0 installed (auth_mellon 0.14.0 is the latest in the yum repository.)
When I attempt to logout by redirecting to http://example.com/mellon/logout?ReturnTo=http://example.com
I get a 400 bad request error in my browser (google chrome on windows 10).
If I look in the mellon_diagnostics log file I see:

[APLOG_ERR auth_mellon_handler:729] Error processing logout request message. Lasso error: [-407] invalid message

I can find no information to help diagnose this issue.
How do I resolve this?

**Comment by thijskh** [comment]
Reading the code (since you are using such an old version) I think you will only end up on that error message if you initialize a SAML Logout request from the IdP. That's something different from what you describe that you do (redirect to the mentioned url).
