### ISSUE TITLE
Using Mellon ENV Variables in rewriterules? Looking for some guidance

### ISSUE THREAD

**Issue by icsy7867** [latchset/mod_auth_mellon#114]
I am curious if this is doable.  I am thinking that due to the phases in apache, the variable I want to test isnt available yet.   This combined with my poor regex and rewrite experience is giving me a headache on this, and I was hoping someone smarter than me could offer some help or guidance.

So here is a simple scenario.  I am making a bookmarks page with helpful and common bookmarks and I have deployed https://github.com/pawelmalak/flame and https://github.com/bastienwirtz/homer to test.  These are all in docker containers and apache is being used as a reverse proxy with mellon.

By itself, mellon is working 100% fine and as expected.  But my goal is to change the reverse proxy path based on the user.  So here comes my rewriterules.

```
RewriteCond  %{MELLON_NAME_ID}  ^.*johnsmith.*$ [NC]
RewriteRule ^/(.*)$ "http://flame:5005/$1" [P,L]

RewriteCond  "%{LA-U:REMOTE_USER}"  ^((?!johnsmith)).* [NC]
RewriteRule ^/(.*)$ "http://homer:8080/$1" [P]
```

I have tried several variables and types for the rewrite condition:

- %{MELLON_NAME_ID}
- %{LA-U:MELLON_NAME_ID}
- %{REMOTE_USER}
- %{LA-U:REMOTE_USER}
- etc...

However when I log into the site, the second rule is always triggered which means the first rule is never true.  So either i am missing somehting, or what I want to do is not possible.  Thanks!

**Comment by thijskh** [comment]
Indeed, Rewrites are usually done pre-auth. I do not have personal experience with the Lookahead feature and whether it should work with the way mod_mellon works. I can tell you in general to verify that the environment variables you want to use are indeed available at the point where you do the rewrite, i.e. they are in the same <Location> section or in a section that has `MellonEnable info` set.

**Comment by icsy7867** [comment]
> Indeed, Rewrites are usually done pre-auth. I do not have personal experience with the Lookahead feature and whether it should work with the way mod_mellon works. I can tell you in general to verify that the environment variables you want to use are indeed available at the point where you do the rewrite, i.e. they are in the same `<Location>` section or in a section that has `MellonEnable info` set.

Thanks for this!  This brings up a few questions though.  From reading the apache docs, using a rewriterule in a location block is a bit of a no-no and discouraged.
https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html#rewriterule
```
Although rewrite rules are syntactically permitted in [<Location>](https://httpd.apache.org/docs/2.4/mod/core.html#location) and [<Files>](https://httpd.apache.org/docs/2.4/mod/core.html#files) sections (including their regular expression counterparts), this should never be necessary and is unsupported. A likely feature to break in these contexts is relative substitutions.
```

Although surprisingly if I move my logic to the <Location /> block, I start getting a "forbidden" response.  So there is definitely some nuisance here that I dont understand.

However, in the location block I do have MellonEnable 'AUTH'.  From reading the documentation this "Auth" should also have the same variables available as MellonEnable Info shouldn't it?

Is there an easy way to verify that the variable I want are available with what I am trying to do?  Other than reloading a website and testing again, I am not sure how to test for that.

**Comment by icsy7867** [comment]
Whew! I couldnt put this one down.  But no matter what I did, or what variables I used I couldnt get this to work.  I tried the look ahead variables (LA-U variables, I tried some SetEnvIf, IF/Else statements, nothing seemed to be able to capture those variables from mellon.  They must be done at the very very end of the chain.

So, my solution was to add yet another (3 reverse proxies in total, but only 2 are really needed) reverse proxy.  My docker contains use an nginx reverse proxy for SSL/HTTPS for all of the other containers, then the apache mellon, then another apache container to handle the "splitting".

I am performing a variable reverse proxy depending on whether or not a user is a member of a specific group.  So the last apache reverse proxy looks like this
```
<VirtualHost _default_:80>
ServerName https://tools.company.com

   ProxyRequests On
   ProxyPreserveHost On
   RewriteEngine On

# This basically means, if the request header X-Webauth-Groups contains "Some AD Group", use
# The flame reverse proxy, and (L) stop running other rules
RewriteCond %{HTTP:X-Webauth-Groups} ^(.*)Some\sAD\sGroup(.*)$
RewriteRule ^/(.*) http://flame:5005/$1 [P,L]

# otherwise, use the homer reverse proxy.
RewriteRule ^/(.*) http://homer:8080/$1 [P]

</VirtualHost>
```

Where Flame and Homer are backend web servers running in docker containers.  The trick with this, is we are using a header passed from Mellon to grab our info and then perform our proxypass rewrites.  Pretty simple... except the sytanx was a PITA.  I wasnt using the correct capitalization for my header values which I think was causing it to be null.

**Comment by thijskh** [comment]
Thank you for sharing the experience so people can find it for future reference. I don't think there's currently anything Mellon can change in this regard so I'm closing the issue.
