### ISSUE TITLE
Need to run autogen.sh before configure

### ISSUE THREAD

**Issue by hokuda** [latchset/mod_auth_mellon#123]
I need to run autogen.sh before configure to buld the module, but the README.md does not mention it.

**Comment by thijskh** [comment]
The documentation assumes you're using a released version. Running `autogen.sh` is indeed required when building from a git checkout. We could expand the docs to mention this.

**Comment by thijskh** [comment]
Fixed in e77ab1bb6acfda122b991b29bec5fdc4851e1561
