### ISSUE TITLE
Support for newer versions of openss

### ISSUE THREAD

**Issue by pjelou** [latchset/mod_auth_mellon#133]
Can't run the module on alpine above 3.17 as it has a newer version of openssl. 
When running on alpine above 3,16 fails with the following errot
` /usr/local/apache2/conf/httpd.conf: Cannot load modules/mod_auth_mellon.so into server: Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /usr/local/apache2/modules/mod_auth_mellon.so`

Same code if a base image of httpd using alpine of 15 and below is used.

**Comment by simo5** [comment]
Sounds like an alpine bug or a bug of whoever provides you with the binaries you use.
The code itself works with whatever version you compile its dependencies against (libxml and the like).

**Comment by pjelou** [comment]
Thank you very much @simo5  for your explanation. 
I will look to see where the binaries are compiled and it makes sense that they're not compiled on the latest version of alpine. 
Thank you again for your time and effort.

**Comment by pjelou** [comment]
ARG APACHE_VERSION=2.4.58-alpine3.18

FROM httpd:${APACHE_VERSION} AS build

ARG MELLON_VERSION=0.18.1
ARG XMLSEC_VERSION=1.3.2
ARG LASSO_VERSION=2.8.2

RUN apk --update add \
  autoconf \
  automake \
  curl-dev \
  g++ \
  glib-dev \
  libtool \
  libxml2-dev \
  make \
  perl-dev \
  python3 \
  zlib-dev \
  curl \
  xmlsec xmlsec-dev \
  py3-pip  py3-six apr-dev \
  apache2-dev

# Install lasso
RUN mkdir /tmp/lasso && \
  curl -L https://dev.entrouvert.org/releases/lasso/lasso-${LASSO_VERSION}
.tar.gz | tar -xvz -C /tmp/lasso --strip 1 && \
  cd /tmp/lasso && \
  ./configure --disable-perl LASSO_CFLAGS='-I/usr/include/xmlsec1
-I/usr/include/openssl -DXMLSEC_CRYPTO=\"openssl\" -DXMLSEC_CRYPTO_OPENSSL=1
-DXMLSEC_CRYPTO_DYNAMIC_LOADING=0 -D__XMLSEC_FUNCTION__=__func__
-DXMLSEC_NO_FTP=1 -DXMLSEC_NO_MD5=1 -DXMLSEC_NO_GOST=1
-DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/include/glib-2.0
-I/usr/lib/glib-2.0/include -I/usr/include/libxml2' && \
  make && \
  make install

# Install mod_auth_mellon
RUN mkdir /tmp/mod_auth_mellon && \
  curl -L https://github.com/latchset/mod_auth_mellon/releases/download/v
${MELLON_VERSION}/mod_auth_mellon-${MELLON_VERSION}.tar.gz | tar -xvz -C
/tmp/mod_auth_mellon --strip 1 && \
  cd /tmp/mod_auth_mellon && \
  aclocal && \
  autoheader && \
  autoconf && \
  ./configure --with-apxs2=/usr/local/apache2/bin/apxs && \
  make && \
  make install

FROM httpd:${APACHE_VERSION}
RUN apk --no-cache add glib curl libxslt libltdl

# copy mellon_create_metadata.sh
COPY --from=build /tmp/mod_auth_mellon/mellon_create_metadata.sh /usr/sbin/
RUN chmod +x /usr/sbin/mellon_create_metadata.sh

# Copy compiled mellon
COPY --from=build /usr/local/apache2/modules/mod_auth_mellon.so
/usr/local/apache2/modules/mod_auth_mellon.so
COPY --from=build /usr/local/lib/liblasso* /usr/local/lib/
COPY --from=build /usr/local/lib/libxmlsec1* /usr/local/lib/

# alter httpd.conf to include files from conf.d and open 443
RUN sed -i '/<IfModule ssl_module>/a Listen 443'
/usr/local/apache2/conf/httpd.conf && \
    sed -i '/<IfModule proxy_html_module>/i IncludeOptional conf.d/*.conf'
/usr/local/apache2/conf/httpd.conf
Pavel Jeloudovski
mobile:+1 9024482019
My LinkedIn profile <http://il.linkedin.com/in/paveljeloudovski>
Knowledge is knowing a tomato is a fruit; Wisdom is not putting it in a
fruit salad.

**Comment by pjelou** [comment]
Here is a Dockerfile example to build the module
the solution to the problem is building lasso with the proper arguments

`ARG APACHE_VERSION=2.4.58-alpine3.18

FROM httpd:${APACHE_VERSION} AS build

ARG MELLON_VERSION=0.18.1
ARG XMLSEC_VERSION=1.3.2
ARG LASSO_VERSION=2.8.2

RUN apk --update add \
  autoconf \
  automake \
  curl-dev \
  g++ \
  glib-dev \
  libtool \
  libxml2-dev \
  make \
  perl-dev \
  python3 \
  zlib-dev \
  curl \
  xmlsec xmlsec-dev \
  py3-pip  py3-six apr-dev \
  apache2-dev

# Install lasso
RUN mkdir /tmp/lasso && \
  curl -L https://dev.entrouvert.org/releases/lasso/lasso-${LASSO_VERSION}.tar.gz | tar -xvz -C /tmp/lasso --strip 1 && \
  cd /tmp/lasso && \
  ./configure --disable-perl LASSO_CFLAGS='-I/usr/include/xmlsec1 -I/usr/include/openssl -DXMLSEC_CRYPTO=\"openssl\" -DXMLSEC_CRYPTO_OPENSSL=1 -DXMLSEC_CRYPTO_DYNAMIC_LOADING=0 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_FTP=1 -DXMLSEC_NO_MD5=1 -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2' && \
  make && \
  make install

# Install mod_auth_mellon
RUN mkdir /tmp/mod_auth_mellon && \
  curl -L https://github.com/latchset/mod_auth_mellon/releases/download/v${MELLON_VERSION}/mod_auth_mellon-${MELLON_VERSION}.tar.gz | tar -xvz -C /tmp/mod_auth_mellon --strip 1 && \
  cd /tmp/mod_auth_mellon && \
  aclocal && \
  autoheader && \
  autoconf && \
  ./configure --with-apxs2=/usr/local/apache2/bin/apxs && \
  make && \
  make install

FROM httpd:${APACHE_VERSION}
RUN apk --no-cache add glib curl libxslt libltdl

# copy mellon_create_metadata.sh
COPY --from=build /tmp/mod_auth_mellon/mellon_create_metadata.sh /usr/sbin/
RUN chmod +x /usr/sbin/mellon_create_metadata.sh

# Copy compiled mellon
COPY --from=build /usr/local/apache2/modules/mod_auth_mellon.so /usr/local/apache2/modules/mod_auth_mellon.so
COPY --from=build /usr/local/lib/liblasso* /usr/local/lib/
COPY --from=build /usr/local/lib/libxmlsec1* /usr/local/lib/

# alter httpd.conf to include files from conf.d and open 443
RUN sed -i '/<IfModule ssl_module>/a Listen 443' /usr/local/apache2/conf/httpd.conf && \
    sed -i '/<IfModule proxy_html_module>/i IncludeOptional conf.d/*.conf' /usr/local/apache2/conf/httpd.conf`
