### ISSUE TITLE
EntitiesDescriptor - Multiple SP entityID's not working

### ISSUE THREAD

**Issue by bglinkerman** [latchset/mod_auth_mellon#137]
The way I read the documentation is that Mellon supports multiple SP entityID's 

> EntityDescriptor is a container for all properties belonging to the entity identified by the entityID name. SAML metadata allows a single metadata document to describe multiple entities. In that case the top level element will be a <EntitiesDescriptor> element which will contain one or more <EntityDescriptor> elements. If the metadata describes only a single entity, it is permissible to just use a <EntityDescriptor>.

In my situation I have an application deployed in two kubernetes clusters. You can hit the application using 1 of 3 URLs:

* GSLB URL (crud.corp.com)
* Cluster1-specific URL (crud.kcluster1.corp.com)
* Cluster2-specific URL (crud.kcluster2.corp.com)
 
We are using Ping Federate as our IdP and have configured 3 profiles on the IdP (one for each of the about URLs/entityIDs).

I then have apache mod_auth_mellon configured with these 3 entities, nested inside of an EntitiesDescriptorblock:

```xml
<EntitiesDescriptorxmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds=http://www.w3.org/2000/09/xmldsig#>
  
  <EntityDescriptor entityID=https://crud.corp.com>
    <SPSSODescriptorprotocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor use="signing">
        <ds:KeyInfoxmlns:ds=http://www.w3.org/2000/09/xmldsig#>
          <ds:X509Data>
            <ds:X509Certificate>MIICsjCCAZoCCQC9jlZ5G9LVlDANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBj...</ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </KeyDescriptor>
      <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat>
      <SingleLogoutServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location=https://crud.corp.com/sso/logout/>
      <AssertionConsumerServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location=https://crud.corp.com/sso/postResponse index="0"/>
    </SPSSODescriptor>
  </EntityDescriptor>
  
  <EntityDescriptorentityID=https://crud.kcluster1.corp.com>
    <SPSSODescriptorprotocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor use="signing">
        <ds:KeyInfoxmlns:ds=http://www.w3.org/2000/09/xmldsig#>
          <ds:X509Data>
            <ds:X509Certificate>MIICsjCCAZoCCQC9jlZ5G9LVlDANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBj...</ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </KeyDescriptor>
      <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat>
      <SingleLogoutServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location=https://crud.kcluster1.corp.com/sso/logout/>
      <AssertionConsumerServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location=https://crud.kcluster1.corp.com/sso/postResponse index="0"/>
    </SPSSODescriptor>
  </EntityDescriptor>
  
  <EntityDescriptorentityID=https://crud.kcluster2.corp.com>
    <SPSSODescriptorprotocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor use="signing">
        <ds:KeyInfoxmlns:ds=http://www.w3.org/2000/09/xmldsig#>
          <ds:X509Data>
            <ds:X509Certificate>MIICsjCCAZoCCQC9jlZ5G9LVlDANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBj...</ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </KeyDescriptor>
      <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat>
      <SingleLogoutServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location=https://crud.kcluster2.corp.com/sso/logout/>
      <AssertionConsumerServiceBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location=https://crud.kcluster2.corp.com/sso/postResponse index="0"/>
    </SPSSODescriptor>
  </EntityDescriptor>
  
</EntitiesDescriptor>

```

I’ve also configured apache with a virtual host for each of these URLs and have UseCanoncialNames enabled so that Apace retains the DNS name the user entered into the browser.

```
    <VirtualHost *:443>
      ServerName crud.corp.com
      UseCanonicalName On
      Include conf.d/mellon-sso.conf
    </VirtualHost>
      
    <VirtualHost *:443>
      ServerName crud.kcluster1.corp.com
      UseCanonicalName On
      Include conf.d/mellon-sso.conf
    </VirtualHost>
      
    <VirtualHost *:443>
      ServerName crud.kcluster2.corp.com
      UseCanonicalName On
      Include conf.d/mellon-sso.conf
    </VirtualHost>
```

However, the SAML AuthnRequest always contains the entityID of the first record inside of EntitiesDescriptor (in this case crud.corp.com). When I hit the cluster-specific URLs the resulting authentication attempt fails.

And for reference, here is my mellon config:

```
<Location />
    <IfModule mod_auth_mellon.c>
      Require                valid-user
      AuthType               "Mellon"
      MellonSecureCookie     On
      MellonEnable           auth
      MellonSessionLength    3600
      MellonSPMetadataFile   /etc/httpd/mellon/sp.cert
      MellonSPPrivateKeyFile /etc/httpd/mellon/sp.key
      MellonSPCertFile       /etc/httpd/mellon/sp.xml
      MellonIdPMetadataFile  /etc/httpd/mellon/idp-metadata.xml
      MellonEndpointPath     /sso
    </IfModule>
</Location>
```

How do I get multiple entityIDs to work within EntitiesDescriptor or is this not fully supported by mellon?

**Comment by thijskh** [comment]
Hi, although I do not have such a hosted setup currently myself, I suspect that in each virtual host you need to specify the `MellonSPentityId` variable so that virtual host knows which mellon SP to present itself as. Does that help?

**Comment by bglinkerman** [comment]
Thanks @thijskh for the recommendation. I tried this out and didn't have any different outcome.

**Comment by thijskh** [comment]
Ah, I missed that you use `MellonSPMetadataFile` to read in the SAML SP metadata for Mellon.

`MellonSPMetadataFile` will load the first available entity descriptor in the given file.

If you want to configure different virtual hosts with different properties, you need to either supply each with its own metadata. Or, you configure the SP entirely with the `Mellon*` Apache keywords which works just as well (or better). Because I'm not sure what value it adds to configure them all via XML in this way.
