### ISSUE TITLE
Extra dependency not documented - libcurl

### ISSUE THREAD

**Issue by clmcavaney** [latchset/mod_auth_mellon#146]
G'day, when I was running `configure` on a relatively vanilla Ubuntu 22.04LTS environment, I found that I needed to also install `libcurl-dev` (I chose specifically `libcurl4-openssl-dev`).

My suggestion is that this:
https://github.com/latchset/mod_auth_mellon/blob/2c7e8795ae7f02bff2a73ff71d7a0721afde922c/README.md?plain=1#L13

should be "five dependencies" and include `libcurl-dev` in the list below that reference point.

**Comment by thijskh** [comment]
Indeed, this was added for the Artifact binding. It's not currently optional so I'll indeed document it. Thanks for reporting!

**Comment by clmcavaney** [comment]
Thanks Thijs.
I note it still says "four" above the list though.

**Comment by thijskh** [comment]
Thanks, I've fixed that now
