### ISSUE TITLE
Strange behavior with a known-good metadata file

### ISSUE THREAD

**Issue by mdraugh** [latchset/mod_auth_mellon#18]
This is strange.  I'm trying to set up a new site with exactly the same IdP metadata as over 20 existing sites (the IDP is managed by NOAA), and it's not working.  I get this in the server logs:

Apr 20 09:23:21 ELUSU httpd[102320]: [auth_mellon:error] [pid 102320] [client 172.16.39.9:44924] Error adding metadata "/etc/httpd/saml2/idp-prod.xml" to lasso server objects. Lasso error: [-205] Parsed XML is invalid., referer: https://elusu.nesdis-hq.noaa.gov/mellon/login?ReturnTo=https%3A%2F%2Felusu.nesdis%2Dhq.noaa.gov%2F&IdP=(null)
Apr 20 09:23:21 ELUSU httpd[102320]: [auth_mellon:error] [pid 102320] [client 172.16.39.9:44924] Error adding IdP to lasso server object. Please verify the following configuration directives: MellonIdPMetadataFile and MellonIdPPublicKeyFile., referer: https://elusu.nesdis-hq.noaa.gov/mellon/login?ReturnTo=https%3A%2F%2Felusu.nesdis%2Dhq.noaa.gov%2F&IdP=(null)

I've already tried:
- Recopying the metadata file from a working server
- Temporarily setting SELinux to Permissive
- Verifying with the IdP maintainer that they haven't changed metadata on their end
- Running the XML through an XML checker; it came out clean

What am I missing here?  I thought I had this down, and apparently I don't.

(Apache 2.2 on RHEL 7.8, same as the other 20 systems.)

<MR>

**Comment by thijskh** [comment]
Can you please attach the exact metadata file used?

**Comment by mdraugh** [comment]
Well, except for the actual certificate I can.

<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="noaa-online-idp">
<IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
-- redacted --
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</KeyDescriptor>
<ArtifactResolutionService index="0" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/ArtifactResolver/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/IDPSloPOST/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPSloPOST/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/IDPSloSoap/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/IDPMniRedirect/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPMniRedirect/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/IDPMniPOST/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPMniPOST/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/IDPMniSoap/metaAlias/noaa-online/idp"/>
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
</NameIDFormat>
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
</NameIDFormat>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/SSORedirect/metaAlias/noaa-online/idp"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/SSOPOST/metaAlias/noaa-online/idp"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/SSOSoap/metaAlias/noaa-online/idp"/>
<NameIDMappingService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/NIMSoap/metaAlias/noaa-online/idp"/>
<AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/AIDReqSoap/IDPRole/metaAlias/noaa-online/idp"/>
<AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:URI" Location="https://sso.noaa.gov:443/openam/AIDReqUri/IDPRole/metaAlias/noaa-online/idp"/>
</IDPSSODescriptor>
</EntityDescriptor>

**Comment by thijskh** [comment]
If I test it with the above metadata verbatim I get the same errors (and some LASSO warnings above) in the Apache error log. When I replace `-- redacted --` with an existing, working certificate I get no metadata parsing errors. So perhaps actually the certificate is the issue.

Why can't you share a public certificate? Nothing secret about that?

**Comment by mdraugh** [comment]
For some reason I thought the private key was included in that.  Okay, what the hell.  Bear in mind that I have 20-odd other installation of this exact metadata file and they all work.

```
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="noaa-online-idp">
<IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
MIIFDjCCA/agAwIBAgIDAh5EMA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNVBAYTAlVTMRgwFgYDVQQK Ew9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMDUEtJMRgwFgYDVQQDEw9E T0QgSUQgU1cgQ0EtMzgwHhcN
MTcwNzI2MjA1MzExWhcNMjAwNzI2MjA1MzExWjBpMQswCQYDVQQG EwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsTA1BL STENMAsGA1UECxMERElTQTEVMBMGA1UEAxMMc3NvLm5vYWEu
Z292MIIBIjANBgkqhkiG9w0BAQEF AAOCAQ8AMIIBCgKCAQEAokNxbwKnGsMvojXOa8TV6I62qapOzPIh6igvMJqb/JF4pGCwuCDWlbXA BxThV5BE8mnsuNDIP2TFR9Ojl/wBuIfWs4iShaw4k1Mb6cu2Supa/wBJ0AtZGHft3fqMNWFx
cYTK olDqUVZZE3ytoBGNpKs68EA9kr8CQqC0WHGjQrGkODMogzKR//u9hKGCRuo1YP5wSJ4dX/oNfadC xOCPhx0nSZblz7OnYOWgv7g+mZwftXSl4qO89ck7rCspnjfPSnBlXyJO6A1rEPf78tOwxYwVNAnu YVhuGzhVkr8I15Y6k+aya8fwhAd81J8cuzRyJGg4GT5F5MZoI42OC3nt7wIDAQABo4IByTCCAcUw HwYDVR0jBBgwFoAUjsW5zPzOjlO0Ks7oESrPmylsZ8owHQYDVR0OBBYEFM5U4xPEC945d+/2aDMX NUhPbdwtMGcGCCsGAQUFBwEBBFswWTA1BggrBgEFBQcwAoYpaHR0cDovL2NybC5kaXNhLm1pbC9z aWduL0RPRElEU1dDQV8zOC5jZXIwIAYIKwYBBQUHMAGGFGh0dHA6Ly9vY3NwLmRpc2EubWlsMA4G A1UdDwEB/wQEAwIFoDA5BgNVHR8EMjAwMC6gLKAqhihodHRwOi8vY3JsLmRpc2EubWlsL2NybC9E T0RJRFNXQ0FfMzguY3JsMIGNBgNVHREEgYUwgYKCDHNzby5ub2FhLmdvdoIVc3NvLWVhc3QuY3Nw Lm5vYWEuZ292ghVzc28td2VzdC5jc3Aubm9hYS5nb3aCFnNzby1ub3J0aC5jc3Aubm9hYS5nb3aC FnNzby1zb3V0aC5jc3Aubm9hYS5nb3aCFHNzby1wYWMuY3NwLm5vYWEuZ292MBYGA1UdIAQPMA0w CwYJYIZIAWUCAQsnMCcGA1UdJQQgMB4GCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUIAgIwDQYJ KoZIhvcNAQELBQADggEBAJd/A0HQoHYwe0jGVJEbh/rpTIZaS68gI3D7CpH2MnEfUd5SLok4mZrw XWXbVyOsRIUQeIFAqvQIduHNQBqwkF4O1ht6KH3QaRYHTBiJHQbKuqokI+zQZAUUm9BeVVQTSWil nm1qk36uYP3ITwQKdnm3xlnDQSrcUneahiOseir1W3VY3dJFB7RJiZWEb6tzHyUQX0+CMK4ZtkwZ 5IF+hdgy4RIUkPsK7zlp+mMSg6YlUOZmXEEdO79ErZb7M4YH1Id6dIj5st2HNBSwp6rAj59lf4QC 2mdtwoqSVjg4oLq9xYWQH5mR6i9E3liUgXb7fhrPG6/7R2yUpIThdlfp1yk=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</KeyDescriptor>
<ArtifactResolutionService index="0" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/ArtifactResolver/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/IDPSloPOST/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPSloPOST/metaAlias/noaa-online/idp"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/IDPSloSoap/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/IDPMniRedirect/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPMniRedirect/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/IDPMniPOST/metaAlias/noaa-online/idp" ResponseLocation="https://sso.noaa.gov:443/openam/IDPMniPOST/metaAlias/noaa-online/idp"/>
<ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/IDPMniSoap/metaAlias/noaa-online/idp"/>
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
</NameIDFormat>
<NameIDFormat>
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
</NameIDFormat>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.noaa.gov:443/openam/SSORedirect/metaAlias/noaa-online/idp"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.noaa.gov:443/openam/SSOPOST/metaAlias/noaa-online/idp"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/SSOSoap/metaAlias/noaa-online/idp"/>
<NameIDMappingService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/NIMSoap/metaAlias/noaa-online/idp"/>
<AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://sso.noaa.gov:443/openam/AIDReqSoap/IDPRole/metaAlias/noaa-online/idp"/>
<AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:URI" Location="https://sso.noaa.gov:443/openam/AIDReqUri/IDPRole/metaAlias/noaa-online/idp"/>
</IDPSSODescriptor>
</EntityDescriptor>

```
I actually took the file from this server (ELUSU) from one of the working ones.

<MR>

**Comment by thijskh** [comment]
This parses just fine for me with mod mellon... so cannot really tell from here but there must be _something_ different about this server that exhibits the problem.

**Comment by mdraugh** [comment]
There must be, but I'm damned if I can see it.  I have to figure the error messages is wrong, and something other than the XML itself is stopping the server from reading/processing that metadata.  I'm about ready to pull off the whole HTTPD and reinstall it.

**Comment by vittala** [comment]
Have you checked if the trusted CAs on the servers are all the same?

The certificate issuer is "C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DOD ID SW CA-38" - is this trusted on the server you're having problems with?

**Comment by mdraugh** [comment]
No, but it is on the IdP, which is what I thought matters.  None of my other hosts trust that CA either.  They don't need to, I don't think, because the host isn't trying to validate anything.

**Comment by thijskh** [comment]
@mdraugh Did you get any further with debugging this?
