### ISSUE TITLE
Mellon apache variables are set in null RequestHeader

### ISSUE THREAD

**Issue by jhonj98** [latchset/mod_auth_mellon#19]
Hello everyone, 

I would like you to help my with something that I think is straightforward but I haven't been able to do it, I need to expose some mellon environmental variables comming from the idp to my node js backend in request header with RequestHeader, This is what I did in my config file regarding mellon:

           <Location />
                # Add information from the mod_auth_mellon session to the request.
                MellonEnable "info"
                # MellonSessionLength 120
                # Configure the SP metadata
                # This should be the files which were created when creating SP metadata.
                MellonSPPrivateKeyFile /etc/apache2/mellon/http_XXXXXXX_saml.key

                MellonSPCertFile /etc/apache2/mellon/http_XXXXXXX_saml.cert
                MellonSPMetadataFile /etc/apache2/mellon/http_XXXXXXX_saml.xml

                # IdP metadata. This should be the metadata file you got from the IdP.
                MellonIdPMetadataFile /etc/apache2/mellon/idp-metadata.xml

                MellonSamlResponseDump On
                MellonIDP "IDP"
                MellonSetEnv "username" "username"

                RequestHeader set MELLON_name "%{MELLON_name}e"
                RequestHeader set MELLON_emailaddress "%{MELLON_emailaddress}e"

                # The location all endpoints should be located under.
                # It is the URL to this location that is used as the second parameter to the metadata generation script.
                # This path is relative to the root of the web server.
                MellonEndpointPath /callback
        </Location>

        # This is a location that will trigger authentication when requested.
        <Location />
              # This location will trigger an authentication request to the IdP.
                MellonEnable "auth"
        </Location>

I can see the variables in node js after setting in the config file, but they have the value "(null)", all the process of federating is working pretty well, but this part of my backend knows the attributes has been really difficult, please advice.

Thank you very much.

Jhon Jairo.

**Comment by jhonj98** [comment]
I could resolve this issue by myself, it was realted with the name of the attribute, I had to specify que complete name that included http://......../emailaddress.

I would like you to include mellon diagnostics in linux jessie, now is really difficult detect some things related with MELLON environment variables.  

Thank you in advanced.

Jhon Jairo

**Comment by thijskh** [comment]
Good to hear that you solved it. Mellon diagnostics will be enabled in the next Debian release bullseye, and are available via the backports repository of stretch and buster. Jessie is out of support by Debian so will not be updated anymore.

**Comment by jhonj98** [comment]
Thank you, now I see that that I have to upgrade my system to stretch. thank you.

Version | support architecture | schedule
-- | -- | --
Debian 8 “Jessie” | i386, amd64, armel and armhf | from 17th June 2018 to June 30, 2020
Debian 9 “Stretch” | i386, amd64, armel, armhf and arm64 (to review before start) | 2020 to June 2022
