### ISSUE TITLE
Incompatible with mod_ruid2

### ISSUE THREAD

**Issue by xhejtman** [latchset/mod_auth_mellon#25]
If I use mod_ruid2, I cannot use mod_auth_mellon, as global cache locks result in permission denied like this:
[Mon May 25 09:46:22.065689 2020] [auth_mellon:error] [pid 12952] apr_global_mutex_lock() failed [13]: Permission denied

It's because the lock is created by www-data process, but a child runs under ruid's specified uid. 

Is there a way to fix it?

**Comment by thijskh** [comment]
I'm not sure since I'm not very familiar with ruid2. Maybe it helps if you propose a concrete pull request with what you'd like to see changed?
