### ISSUE TITLE
RelayState may be blank?

### ISSUE THREAD

**Issue by APEX-DevMan** [latchset/mod_auth_mellon#26]
Hello, I have implemented mod_auth_mellon version 0.14 on our Apache server which is acting as a reverse proxy to redirect traffic after authentication to our WebLogic server. During my testing, I get a success response back from our internal IDP but I have a feeling the RelayState is either never being populated from me, the SP, or the IDP is losing it and not redirecting back to the URL the request started at after authentication. Also, mellon never redirects to the IDP automatically. I have to do something like a button click and send to my IDP's URL specific to our entityID in order to start the process. When I visit my endpoint (https://ourdomain.gov/saml2) it throws a 404 error. The "saml2" directory does not exist in our "/var/www/html/" structure because I thought a mellon handler would "handle" anything going to the endpoint directory (or downline of it)? 

I am on RHEL v7 where Apache lives and installed the mellon module with a simple yum command. Because of that, the module did not have Mellon Diagnostics enabled so I can't figure out how to enable it for better troubleshooting.

I even tried installing the newest version (0.16) from source so I could see it resolved our issue and to enable diagnostics during the configure but our RHEL was missing some modules to do ./configure and make install that I couldn't figure out. 

Any insight as to how I could spy the RelayState coming from our SP going to the IDP or from the IDP after the authnrequest? My only tool so far is using the Network in Chrome Dev Tools. Our agency won't allow third party extensions and even fiddler won't work in our environment to spy all requests. :( 

I feel like I am really close to this working. I even see in my apache ssl_access_log (in debug mode) the NameIDFormat in each line of the log after the postResponse request.

Any assistance with this issue would be greatly appreciated and I look forward to hearing any troubleshooting tips you could provide. :)

**Comment by APEX-DevMan** [comment]
Is anyone even monitoring this area any longer?

**Comment by simo5** [comment]
Yes we do see these, but I have no comments on your "issue"(*). It looks like you have an environment in which you can't get any useful debugging information and an unclear problem to me.

Can you provide at least your configuration and specifically how you configured your MellonEndpointPath and any logs?

Help us help you.

(*) note: this is not a help forum but an issue tracker

**Comment by thijskh** [comment]
Closing as there's no further information supplied. We'd need at least your configuration and what you're doing exactly. It would indeed be helpful to enable Mellon Diagnostics. Using chrome dev tools should give you quite some ways to inspect what happens with a RelayState parameter btw.
