### ISSUE TITLE
Unsafe use of RAND_bytes()

### ISSUE THREAD

**Issue by jchax** [latchset/mod_auth_mellon#39]
A new session id (16 bytes, 128 bits) is generated using `RAND_bytes()` in `am_generate_id()` but, annoyingly, `RAND_bytes()` is not fork safe so it is possible (and I have seen this _once_) to get the same session ID for two different sessions.

Fortunately, there is an easy fix: in `am_child_init()` call `RAND_seed()` or `RAND_add()` to mix a some entropy into the PRNG state.   You don't need much, just enough to ensure it's different to other instances of the PRNG -- I'd be inclined to grab some entropy from `getrandom()` or `/dev/urandom`.

I think it also makes sense to update `am_new_cache()` to fail if you add the same entry twice.  And try just once more; if it fails a second time then something is seriously amiss and you should abort.

**Comment by simo5** [comment]
What OpenSSL version are you using?
Starting from OpenSSL 1.1.1 fork safety shouldn't be an issue.

**Comment by jchax** [comment]
You're right, it's not.   This is on RHEL/CentOS/OL 7 where we're stuck with openssl 1.0.2 for the next few years.

**Comment by simo5** [comment]
I guess we could accept a patch with conditional code if openssl < 1.1.1 is detected at compile time ...

**Comment by jchax** [comment]
I'll have a crack at it.

**Comment by jchax** [comment]
The person who was interested in fixing this bug has seen sense and moved on to openssl-1.1.1 so rather than clutter up the code with a fix no one actually wants, I'm going to let this slide.

For anyone else seeing this: please use a newer version of openssl, you know it makes sense :)
