### ISSUE TITLE
Docs: "Example to support both SAML and Basic Auth" question

### ISSUE THREAD

**Issue by 3eka** [latchset/mod_auth_mellon#42]
Hi,

 I am looking for option to use LDAP as authentication and found in that chapter:
```
MellonEndpointPath "/sso"
```
then, later:
```
<Location /auth>
```
Is that error? I would expect Location /sso ...

Regards.

**Comment by thijskh** [comment]
`/auth` is the path you want to protect (i.e. your application).
`/sso` is the path where Mellons own endpoints are under, and that are per definition _not_ protected by Mellon. E.g. `/sso/metadata`.

**Comment by 3eka** [comment]
Hi @thijskh 
Thanks for explanation. 

Regards.

P.S: Do you have pointer to working LDAP + mod_mellon authorization example?
I am still struggling to get that working...

**Comment by thijskh** [comment]
I'm afraid that what's in the docs is all I've got on examples.
