### ISSUE TITLE
cert chain for assertion signing?

### ISSUE THREAD

**Issue by rledousa** [latchset/mod_auth_mellon#45]
(This may be a general SAML question, my apologies.  I'm not getting a lot of assistance from my IdP)

My IdP signs the SAML assertion.  In mellon diagnostics I can see that the assertion is decrypted because I see the principal's attributes, but it fails signature verification with [APLOG_ERR auth_mellon_handler.c:2203] Error processing authn response. Lasso error: [440] The profile cannot verify a signature on the message, SAML Response: StatusCode1="urn:oasis:names:tc:SAML:2.0:status:Success", StatusCode2="(null)", StatusMessage="(null)"

My question - what cert does mellon use to verify the signature?  Is it from the system key chain or from the IdP's metadata?  

Thanks ahead of time!

**Comment by thijskh** [comment]
It’s from the IdP metadata. Usually the assertion itself contains the certificate used.

**Comment by rledousa** [comment]
Thank you for the reply.  I thought that was the case.  I'll close this after one final question to make sure I have this all right.  I give the IdP a cert from mellon which the IdP uses to encrypt traffic to mellon.  The IdP's metadata is used for signing.  Because mellon is able to decrypt the traffic but not verify the cert, the only likely reason is that cert in the metadata from the IdP is wrong or incomplete, correct?

**Comment by simo5** [comment]
That's the most likely explanation.

**Comment by rledousa** [comment]
<grumbles again at IdP> thank you for your help!
