### ISSUE TITLE
SigAlg was null error in keycloak

### ISSUE THREAD

**Issue by watercrossing** [latchset/mod_auth_mellon#48]
My keycloak installation works well with other software, but I have failed to set up keycloak with mod_auth_mellon.
I have followed the instructions from the [keycloak manual](https://www.keycloak.org/docs/latest/securing_apps/#_mod_auth_mellon), by 

1. running the `mellon_create_metadata.sh` script as described,
2. copy&pasting the apache configuration
3. uploading the generated `mellon_metadata.xml` to my realm
4. downloading the `idp_metadata.xml` from keycloak as described.

When I now attempt to access the /private path, I get redirected to keycloak showing an `Invalid requester` error. The keycloak logs show: 
`ERROR [org.keycloak.protocol.saml.SamlService] (default task-72) request validation failed: org.keycloak.common.VerificationException: SigAlg was null`, alongside a long stack trace.

Where have I gone wrong?

**Comment by watercrossing** [comment]
Ok, it appears that the `mellon_create_metadata.sh` script does not set `AuthnRequestsSigned="true"` in the `mellon_metadata.xml` file, but keycloak assumes that the Authn requests should be signed. adding `AuthnRequestsSigned="true"`to the xml file fixes this issue .

I guess this is a bug in that the `mellon_create_metadata.sh` script does not specify this variable?

**Comment by simo5** [comment]
Sounds like a missing feature perhaps.

**Comment by jhrozek** [comment]
This is fixed now.
