### ISSUE TITLE
We should add basic CI for testing PRs

### ISSUE THREAD

**Issue by simo5** [latchset/mod_auth_mellon#5]
Either travis or anything else that will do the job really, any takers ?

**Comment by jmaanmies** [comment]
I suggest looking in to just using Github Actions for this.
I set up a small job (lots of room for improvement I bet, first time I used Github Actions) that cleanly builds the project as it is now, we could add running tests etc on to it.

**Comment by jhrozek** [comment]
@jmaanmies contributes github actions which was pushed with 919bce825da3e6b85ae82b7f02fab68cf47f927e, so I'm closing this issue as well.
