### ISSUE TITLE
Mellon auth not working on subsequent hosts

### ISSUE THREAD

**Issue by jdmevo123** [latchset/mod_auth_mellon#90]
In the previous Uninertt installtion I was able to have an initial auth module, i.e. I enabled auth on example.com and then used the auth from this to allow access to sites a.com, b.com ect. This was setup in a location like so:
<Location />
	    MellonEndpointPath /mellon
			AuthType "Mellon"
			MellonEnable "auth"
			Require valid-user
</location>

I could then have subsequent sites setup on different domains with:

<Location /register>
      MellonEndpointPath /mellon
      AuthType "Mellon"
      Require valid-user
      MellonRequire "usertype"
</Location>

After upgrading to this fork, this no loner works and requires me to add MellonEnable "auth" on the other domains, the issue with this is that it doesnt have the saml setup as its an alternate domain.

Any ideas on how I can get this working again?

**Comment by thijskh** [comment]
I don't think anything has changed in this regard re an older version. You can see the changelog to see what the changes are between the (unspecified) version you had earlier and the current version. But maybe the mellon version is not the only thing your changed. I would also look into things like cookie settings and use the web browser's developer toolbar and/or the SAML Tracer browser login to see if everything works cross-domain like you'd expect it to.
