### ISSUE TITLE
Mellon + Azure claims

### ISSUE THREAD

**Issue by GanimanSwift** [latchset/mod_auth_mellon#91]
I am having trouble using values that are returned from Azure after a successful SAML authentication.

I've created a simple PHP script found in the documentation to see the Mellon environment variables. Here are a few sample lines of that output:

`
MELLON_NAME_ID=Abcde12345/AbCdEfGhIjKlMnOp1234567890123456=
`
`
MELLON_IDP=https://sts.windows.net/1234abcd-12ab-12ab-12ab-0123456789ab/
`
`
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/emailaddress=user@domain.com
`

I need to set one value from these claim to another header "X-Remote-User". It seems that I cannot use the values from the claims which have "URLs" in their key names.

I can do this:
`
RequestHeader set X-Remote-User %{MELLON_IDP}e
`

But this does not work, I will get the value "(null)":
`
RequestHeader set X-Remote-User %{MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/emailaddress}e
`

I've tried to use MellonSetEnv like:
`
MellonSetEnv "EMAIL" "http://schemas_xmlsoap_org/ws/2005/05/identity/claims/emailaddress"
`
But I still can only get a "(null)" string in X-Remote-User.  What am I doing wrong?  Or could this be a bug somehow? Even when I use MellonSetEnv, it seems that the environment variable never gets created - I cannot see it in any PHP server variable.

**Comment by GanimanSwift** [comment]
I found this... and it works - but it seems wrong somehow:

https://github.com/Uninett/mod_auth_mellon/issues/166

Feel free to close if this is how it is supposed to work. It seems hard to find this information, so maybe an updated README or something that explains this might be good. Hopefully someone else finds this useful.

**Comment by thijskh** [comment]
I'm not aware of Mellon doing this, the described behaviour suggests that Apache might be changing the variable name before it exports it to the environment. This could be explained by the fact that `.` are (at least officially, so for portability) not allowed in environment variable names.
